AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: GPT Retrieval

Parameters:
  OpenAiApiKey:
    Type: String
  PineconeApiKey:
    Type: String
  ProjectName:
    Type: String
    Default: gpt-retrieval
  LambdasDirectory:
    Type: String
    Default: ../../functions/aws/lambdas
  LayersDirectory:
    Type: String
    Default: ../../functions/aws/layers
  PartSize:
    Type: Number
    Default: "8388608"
    Description: The size of object parts for S3 multipart uploads and byte-range requests. Commonly 8 or 16 MB.

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.9

Resources:
  OpenAiApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}-openai-api-key
      SecretString: !Ref OpenAiApiKey

  PineconeApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}-pinecone-api-key
      SecretString: !Ref PineconeApiKey

  CommonUtilsFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${ProjectName}-common-utils
      ContentUri: !Sub ${LayersDirectory}/common-utils
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  AwsUtilsFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${ProjectName}-aws-utils
      ContentUri: !Sub ${LayersDirectory}/aws-utils
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  UploadNotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${ProjectName}-upload-notification
      # To allow time for the downstream Lambda function(s) to process each batch, set to >(lambda timeout * 6)
      VisibilityTimeout: 300

  UploadNotificationQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref UploadNotificationQueue
      PolicyDocument:
        Id: !Sub ${ProjectName}-upload-notification-policy
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt UploadNotificationQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:s3:::${ProjectName}*

  UploadBucket:
    Type: AWS::S3::Bucket
    DependsOn: UploadNotificationQueuePolicy
    Properties:
      BucketName: !Sub ${ProjectName}-uploads
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins:
              # TODO: restrict to the frontend URL
              - "*"
      NotificationConfiguration:
        QueueConfigurations:
          - Queue: !GetAtt UploadNotificationQueue.Arn
            Event: s3:ObjectCreated:*

  GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-get-upload-url
      Handler: index.handler
      CodeUri: !Sub ${LambdasDirectory}/get_upload_url
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref UploadBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref UploadBucket
      Events:
        GetUploadUrlApi:
          Type: Api
          Properties:
            Path: /uploadUrl/{objectKey}
            Method: get
            RestApiId: !Ref ApiGateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${ProjectName}-api
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: !Ref ProjectName
        paths:
          /uploadUrl/{objectKey}:
            get:
              parameters:
                - name: objectKey
                  in: path
                  required: true
                  type: string
              responses: {
                "200": {
                  "description": "Upload URL",
                  "schema": {
                    "type": "object",
                    "properties": {
                      "uploadUrl": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUploadUrlFunction.Arn}/invocations
                passthroughBehavior: "when_no_templates"
                httpMethod: "POST"
                type: "aws_proxy"
                requestParameters:
                  integration.request.path.objectKey: "method.request.path.objectKey"

  HandleUploadNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-handle-upload-notification
      Handler: index.handler
      CodeUri: !Sub ${LambdasDirectory}/handle_upload_notification
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:30
        - !Ref AwsUtilsFunctionLayer
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref UploadBucket
          PART_SIZE: !Ref PartSize
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt UploadNotificationQueue.Arn
        - S3ReadPolicy:
            BucketName: !Ref UploadBucket
      Events:
        UploadNotificationQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt UploadNotificationQueue.Arn
            BatchSize: 10
            # Note: Lambda may wait up to 20 seconds, even if a smaller batch window is specified.
            MaximumBatchingWindowInSeconds: 10
            ScalingConfig:
              MaximumConcurrency: 50
